FROM python:3.11.2-slim-buster

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r  /code/requirements.txt 


COPY ./app /code/app

# ENV ENVIRONMENT=TEST

CMD ["python","-m","pytest","app/tests"]
# CMD ["pytest","app/tests"]