name: Docker unit test CI

on:
  pull_request:
    branches: 
      - '*'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build -t unit-test --file Dockerfile.test .

    - name: Run tests
      run: docker run unit-test
      
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy Webhook
        run: |
          # Substitua este comando pelo seu comando de deploy usando a URL do webhook
          curl -X POST -d {} ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}